services:
  - type: web
    name: medswift-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: FLASK_SECRET_KEY
        generateValue: true
